# Generated by Django 5.1.2 on 2024-12-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpt2_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='description',
            new_name='gpt2_response',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='name',
        ),
        migrations.AddField(
            model_name='recipe',
            name='prompt_1',
            field=models.TextField(default='default prompt 1'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='prompt_2',
            field=models.TextField(default='default prompt 2'),
        ),
    ]
